### ISSUE TITLE
What shall I do if I want to use pcap with pf_ring?

### ISSUE THREAD

**Issue by astrojhgu** [rust-pcap/pcap#101]
I'm trying to use this lib together with pf_ring. 

pf_ring itself contains a libpcap. If I move libpcap into system lib path and link it with my rust program, will my program automatically be enabled to have the ability of using pf_ring?

Or what else should I do?

**Comment by Wojtek242** [comment]
Did you manage to solve your problem or is this still an open question?

**Comment by astrojhgu** [comment]
> Did you manage to solve your problem or is this still an open question?

No, I have not yet solved this problem. However, I later switched to study another problem and did not fight to solve this problem.

**Comment by Wojtek242** [comment]
Issue is stale, please reopen if needed.
