### ISSUE TITLE
run tests with dynamic analysis tools to detect safety issues (mem leaks, double frees, double closes, ...)

### ISSUE THREAD

**Issue by Trolldemorted** [rust-pcap/pcap#128]
E.g. valgrind with `--track-fds=yes` should have detected #119, and we wouldn't have wasted that much time tracking it down.

**Comment by Wojtek242** [comment]
This should be useful: https://rustc-dev-guide.rust-lang.org/sanitizers.html

**Comment by Wojtek242** [comment]
Would be nice, but not terribly important. Please re-open only if you want to implement this feature.
