### ISSUE TITLE
CI with npcap

### ISSUE THREAD

**Issue by Trolldemorted** [rust-pcap/pcap#134]
The windows tests are not run against npcap, because only [npcap OEM has a silent installer](https://github.com/ebfull/pcap/pull/117#issuecomment-681495849).

I [contacted the npcap project](https://github.com/nmap/npcap/issues/227), and they say we could work something out! I boldly assume you'll receive something you'll have to put into a github actions secret, so you might want to send the email yourselves, but if you are too busy I could do it too.

**Comment by sekineh** [comment]
This info might be useful when both libraries are installed on the same machine:

## Note on WinPcap and npcap DLL search path (WinPcap comes first!)

https://nmap.org/npcap/guide/npcap-devguide.html#npcap-feature-native-dll

> Npcap installs its DLLs into C:\Windows\System32\Npcap\ instead of WinPcap's C:\Windows\System32\. Because of how Windows' DLL search path works, your application will use WinPcap first by default when Npcap and WinPcap coexist, as C:\Windows\System32\ is prior to C:\Windows\System32\Npcap\. So when Npcap and WinPcap coexist, an application that want to use Npcap instead of WinPcap must make C:\Windows\System32\Npcap\ precedent to the C:\Windows\System32\ in the DLL search path. Here are two ways to modify this search path to make your application load Npcap's DLLs first, based on how your application links Npcap/WinPcap's library (wpcap.dll).

**Comment by sekineh** [comment]
In CI, just installing `npcap` only is enough.

**Comment by Wojtek242** [comment]
Resolved by #273
