### ISSUE TITLE
Document how to link against a local, static/dynamic libpcap

### ISSUE THREAD

**Issue by Stargateur** [rust-pcap/pcap#183]
Would be nice to have a vendored feature that statically link the pcaplib. Like openssl crate for example https://docs.rs/openssl/0.10.36/openssl/#vendored

**Comment by Wojtek242** [comment]
Sounds convenient. PRs are welcome :)

**Comment by Wojtek242** [comment]
See my latest comment on the PR:https://github.com/rust-pcap/pcap/pull/195#issuecomment-1100212171

**Comment by Wojtek242** [comment]
See https://github.com/rust-pcap/pcap/pull/195#issuecomment-1100223874

**Comment by Wojtek242** [comment]
> Would be nice to have a vendored feature that statically link the pcaplib. Like openssl crate for example https://docs.rs/openssl/0.10.36/openssl/#vendored

I looked into what openssl does and when it's "vendored" it compiles openssl using the openssl-src crate. We won't do that. But, having thought about it, better support/documentation on how to compile against a locally compiled libpcap is worthwhile. Therefore, this issue is actually broader than #195.

**Comment by Wojtek242** [comment]
As per the discussion in #195, pcap can be compiled against a static libpcap without modifying any pcap code. Therefore, there is no need to expose a new feature as we won't compile libpcap from scratch like openssl does (too much work, too little gain for a small project like this).

However, there should be some documentation in the README as to how static compiling can be achieved so this issue is getting renamed t reflect this.

**Comment by Stargateur** [comment]
Do you think we should use something like https://crates.io/crates/pcap-sys ? we make binding by manually in pcap, but don't use a more "raw" level lib.

**Comment by Wojtek242** [comment]
With https://github.com/rust-pcap/pcap/pull/253, the README was sufficiently updated to provide enough information to anybody who wants to build statically. Ultimately, it's a rust compilation issue, not a `pcap` issue so it's up to the user to consult https://doc.rust-lang.org/cargo/reference/build-scripts.html for static linking. From `pcap`'s point of view, they may have to set `LIBPCAP_VER` if the static library is not the latest version (which is assumed by default).

**Comment by Wojtek242** [comment]
Having said that. If somebody is willing to put the effort into it, PRs along the line of https://doc.rust-lang.org/cargo/reference/build-scripts.html#-sys-packages are welcome.

**Comment by Stargateur** [comment]
it's impossible to statically link for windows, cause the .lib is a fake thing that just say to windows to find a dll.

**Comment by ilya-epifanov** [comment]
here's a `build.rs`:

```rust
fn main() {
    #[cfg(all(unix, feature = "static"))]
    {
        let linux_kernel_headers = std::env::var("LINUX_KERNEL_HEADERS").ok();

        let mut cmake_config = cmake::Config::new("libpcap");

        if let Some(linux_kernel_headers) = linux_kernel_headers {
            cmake_config.define("DISABLE_USB", "ON");
            cmake_config.define("DISABLE_DBUS", "ON");
            cmake_config.define("DISABLE_BLUETOOTH", "ON");
            cmake_config.define("DISABLE_RDMA", "ON");
            cmake_config.define("ENABLE_REMOTE", "OFF");
            cmake_config.define("USE_STATIC_RT", "ON");
            cmake_config.define("BUILD_SHARED_LIBS", "OFF");
            cmake_config.cflag(format!("-I{}", linux_kernel_headers));
        }

        let mut dst = cmake_config.build();
        dst.push("lib");

        println!("cargo:rustc-link-search=native={}", dst.display());
        println!("cargo:rustc-link-lib=static=pcap");
    }
}
```

Cargo.toml:
```toml
[build-dependencies]
pkg-config = { version = "0.3", optional = true }
cc = { version = "1.0", optional = true }
cmake = { version = "0.1", optional = true }

[features]
static = ["pkg-config", "cc", "cmake"]
```

**Comment by stappersg** [comment]
> here's a `build.rs`:
> 
> ```rust
> fn main() {
>     #[cfg(all(unix, feature = "static"))]
>     {
>         let linux_kernel_headers = std::env::var("LINUX_KERNEL_HEADERS").ok();
>      ....
>         println!("cargo:rustc-link-search=native={}", dst.display());
>         println!("cargo:rustc-link-lib=static=pcap");
>     }
>  }
> ```
> 
> Cargo.toml:
> 
> ```
>     ....
> ```
> 
> also `git submodule add https://github.com/the-tcpdump-group/libpcap.git`
> to put `libpcap` source in the root as `build.rs` expects this.


And what the idea about it?   What is the _why_?

Please consider to put the answer in a merge request.


Regards
Geert Stappers


P.S.

For those who want to click on `https://github.com/the-tcpdump-group/libpcap`,
here is the link https://github.com/the-tcpdump-group/libpcap  :smiley:

**Comment by Payn** [comment]
Hello, i'm trying to statically link against 1.5.3 (CentOS 7) version of pcap.

Libraries are present in /usr/lib64

> ls /usr/lib64 | grep pcap
> libpcap.so
> libpcap.so.1
> libpcap.so.1.5.3

My build.rs:

> fn main()
> {
>     println!("cargo:rustc-link-lib=static=pcap");
> }

I'm getting `/usr/bin/ld: cannot find -lpcap` error every time. Tried setting both LIBPCAP_LIBDIR and LIBPCAP_VER with no effect.
Any ideas @Wojtek242 ?
Thanks

**Comment by sudormrfbin** [comment]
> ```rust
>     #[cfg(all(unix, feature = "static"))]
> ```

`cfg` options that determine target system like `cfg(unix)`, `cfg(target_os="windows")` are not supposed to be used with build scripts since it will present [problems with cross compilation][1]:

> It is a mistake to use #[cfg(target_os = …)] in build.rs. This is because #[cfg] refers to the environment in which the build.rs's executable will run, which will be the host (compiler) operating system. It is not the actual compilation target system.
>
> Build scripts have to use Cargo's environmental variables, like CARGO_CFG_TARGET_OS to get actual OS the program is being compiled for.

The alternative would be:

```rust
    #[cfg(feature = "static")]
    if std::env::var_os("CARGO_CFG_UNIX").is_some() {
        let linux_kernel_headers = std::env::var("LINUX_KERNEL_HEADERS").ok();
        // ...
    }
```

[1]: https://users.rust-lang.org/t/compile-for-windows-from-linux-when-have-build-rs/76858
