### ISSUE TITLE
Paths for Upgrading Winpcap to Npcap for Microsoft Windows

### ISSUE THREAD

**Issue by aaplm** [rust-pcap/pcap#196]
In an effort to consolidate our efforts to update the crate to use Npcap over winpcap, I made this ticket so we can centralize any discussion. @Wojtek242 has put forth [two ideas](https://github.com/ebfull/pcap/pull/190#issuecomment-934777143) for upgrading the use of winpcap to Npcap:

1. Update the documentation to support both winpcap and Npcap options and note that the CI pipeline still relies on winpcap
2. Fully replace winpcap with npcap and update the CI pipeline to use Npcap

I was considering a third option that combines both of the above:

3. Update the documentation and CI to use Npcap with winpcap compatibility mode, until we fully remove the old winpcap references
    - Silently install Npcap with the `/winpcap_mode` switch
    - This would also let us get the new updates and improvements that Npcap contributed towards the winpcap libraries

This allows us to keep the same code, but only update the documentation and CI pipeline until we fully remove the dependence on winpcap. The only issue is that we need to get the paid version of Npcap (Npcap OEM). Fortunately, another contributor [asked the nmap folks](https://github.com/nmap/npcap/issues/227) and they mentioned that we just need to email them to get it sorted out.

From my limited testing, installing Npcap with winpcap compatibility worked without any issues. The tests completed successfully and I was able to get a list of devices.

Thoughts? I can reach back out to nmap to get this started if we want to go that route or we can just wait until we fully remove winpcap in one go.

**Comment by stappersg** [comment]
My home has many windows.
As most homes do have windows.
An Igloo is an example of a home without windows.

Point that I trying to make is that this issue should be renamed from
> Paths for Upgrading Winpcap to Npcap
into
> Paths for Upgrading Winpcap to Npcap for Microsoft Windows

Idea behind this request is to make clear that input is needed from people who care about _rust pcap library_ on Microsoft Windows. Also for creating awareness that there is no incentive for people using _rust pcap library_ on other platforms to care about this particular issue.

**Comment by 0b00001101** [comment]
That's fair, I'll update the title. 👌🏼

**Comment by ToshiroZ** [comment]
I do believe upgrading to npcap would be nice. 
I use the library on windows

**Comment by Wojtek242** [comment]
Won't there still be people who use Winpcap (since npcap is paid)? Which would actually mean we (should) always support the winpcap API anyway? If so, then option 3 might be the only way in which case I'd be fine with it. Also, I don't use Windows so I myself have no stake in this ultimately other than I'd rather not have angry people coming along later and complaining about something breaking :-).

**Comment by Wojtek242** [comment]
Also, because I don't use Windows, this isn't something I can implement or even help with so somebody else needs to submit a PR.

**Comment by 0b00001101** [comment]
As far as I know, Npcap is free for personal use and requires a paid license if used in a commercial setting. Npcap is backwards compatible with most of the winpcap interface, but not 100%.

**Comment by Wojtek242** [comment]
> Npcap is backwards compatible with most of the winpcap interface, but not 100%.

Do you think anybody would complain about the differences? I'd assume where they aren't compatible it's in areas people don't really care about.

**Comment by 0b00001101** [comment]
I haven't used Npcap on Windows enough to be fully confident, but I would assume that no one would complain. If they did then, it's hard to justify supporting a library that was deprecated with version 4.1.3 in 08 MAR 2013 to be honest.

**Comment by Wojtek242** [comment]
> If they did then, it's hard to justify supporting a library that was deprecated with version 4.1.3 in 08 MAR 2013 to be honest.

Agreed. If you submit a PR and it passes the tests I think it'll be fine to merge, then wait and see a bit if anybody complains.
