### ISSUE TITLE
`stream` feature/module does not work on Windows

### ISSUE THREAD

**Issue by termhn** [rust-pcap/pcap#201]
The `stream` module does not compile on Windows, and its current implementation seems relatively tightly tied to unix-only structures. I didn't see that documented anywhere and was confused when I got hit with errors on build.

**Comment by sekineh** [comment]
Readme.md says

> Use the capture-stream feature to enable support for streamed packet captures. This feature is supported  only on ubuntu and  macosx.

Better documentation could be possible, I guess.

**Comment by stappersg** [comment]
On Tue, Feb 22, 2022 at 05:19:41AM -0800, Hideki Sekine wrote:
> 
> Better documentation could be possible, I guess.
> 

Stop guessing and come back with merge requests.

**Comment by sekineh** [comment]
I think PRs are welcome as in usual practice.

**Comment by stappersg** [comment]
On Tue, Feb 22, 2022 at 05:38:18AM -0800, Hideki Sekine wrote:
> I think PRs are welcome as in usual practice.

Okay, stop thinking and come back with PRs.

**Comment by stappersg** [comment]
Yes, we agree that somebody (else) should do it.
