### ISSUE TITLE
Packets loading slow or "in groups"

### ISSUE THREAD

**Issue by jabbate19** [rust-pcap/pcap#202]
This may be an issue on my system, but using the example from the rust docs and my custom code the packets come in very slow. It starts, gives me nothing for a while, then all of a sudden all of the packets from when it started to that moment print rapidly. Wireshark running on the side is getting them in real-time. This happens regardless of if Wireshark is open or not, and happens on both MacOS and my Kali VM.

**Comment by Wojtek242** [comment]
Did you close the issue, because you solved your issue? If so, could you let us know what was the problem for future reference?

**Comment by jabbate19** [comment]
I was having the issue that is solved by adding `.timeout()` to the capture. I saw it in the README for MacOS after submitting this. I might be blind, but I didn't see it in the rust crate doc, so I wasn't aware of the issue. I feel that should be added to the rust doc for easier reference, but it is working now!

**Comment by kugel-** [comment]
Hello. I came across this issue after searching why I couldn't capture any packets until waiting long enough to get a swat of packets.

The `.timeout()` hint made me look into the examples. Here I found the `loop` example uses `immediate_mode(true)`. This helped as well. It wasn't clear from the documentation that this is needed for live-capturing (might be an unterlying pcap thing, haven't checked).
