### ISSUE TITLE
Remove unique.rs

### ISSUE THREAD

**Issue by Wojtek242** [rust-pcap/pcap#224]
I was looking through some old issues and from #5 it seems that unique.rs only exists, because it was unstable many years ago. I assume, it is not unstable anymore.

**Comment by Wojtek242** [comment]
Actually it still is nightly only: http://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/std/ptr/struct.Unique.html

**Comment by Stargateur** [comment]
Unique has been removed since a lot of time, I think `NonNull` should work perfectly https://doc.rust-lang.org/std/ptr/struct.NonNull.html
