### ISSUE TITLE
Rename Capture::next to a name that does not suggest it is an iterator

### ISSUE THREAD

**Issue by Wojtek242** [rust-pcap/pcap#225]
`Capture::next` suggests that `Capture` implements an iterator. It does not. Suggest renaming it to `nextpacket` which then mirrors `sendpacket` even though it breaks away from libpcap naming (which it already was not holding that well).

**Comment by Stargateur** [comment]
It's not a bad idea, Capture is more an interface to pcap API. Thus I think I will work to add an iterator.

`read_packet` and `send_packet` make more sense to me.

**Comment by Wojtek242** [comment]
You think an iterator still makes sense? The issue I see with an iterator is that there is no underlying collection and unless copied the packets do not remain so calling `next` on libpcap does not really do the same thing as `next` on a list/vec/map.

**Comment by Wojtek242** [comment]
> You think an iterator still makes sense? The issue I see with an iterator is that there is no underlying collection and unless copied the packets do not remain so calling `next` on libpcap does not really do the same thing as `next` on a list/vec/map.

Actually stream iterators make sense. I don't know why I forgot about them.

**Comment by Wojtek242** [comment]
Closed by https://github.com/rust-pcap/pcap/pull/229
