### ISSUE TITLE
Segmentation faults when running examples

### ISSUE THREAD

**Issue by Wojtek242** [rust-pcap/pcap#254]
```
$ sudo cargo run --example easylisten
  Downloaded bitflags v1.2.1
  Downloaded 1 crate (16.7 KB) in 0.72s
   Compiling bitflags v1.2.1
   Compiling pcap v0.9.2 (/home/wojtek/Workspace/pcap)
    Finished dev [unoptimized + debuginfo] target(s) in 1.40s
     Running `target/debug/examples/easylisten`
Using device wlp4s0
[1]    238107 segmentation fault  sudo cargo run --example easylisten
```

**Comment by Wojtek242** [comment]
Running the example at different commits revealed that 327bb1a is the faulty one.

**Comment by Stargateur** [comment]
we should also test example in the CI

**Comment by Wojtek242** [comment]
We should just test more as our code coverage is only [35-40%](https://rust-pcap.github.io/pcap/index.html) :-). The problem with testing these in CI is that they need to bind to an interface so one should explore how to do that. It 100% can be done in a docker container with veth pairs, but I haven't gotten around to it just yet as it's a lot of work.
