### ISSUE TITLE
Scheduled CI often fails to download windows dll

### ISSUE THREAD

**Issue by Wojtek242** [rust-pcap/pcap#256]
Re-running failed tests usually sorts things out suggesting it's an infrastructure issue.

**Comment by Stargateur** [comment]
do you know why it's look we install winpcap twice ?

```yaml
        run: |
          cinst -y winpcap --version 4.1.3.20161116
          (New-Object System.Net.WebClient).DownloadFile("https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip", "C:/WpdPack.zip")
          Expand-Archive -LiteralPath C:/WpdPack.zip -DestinationPath C:/
          echo "LIB=C:/WpdPack/Lib/x64" >> $env:GITHUB_ENV
```

one with choco and one manually.

**Comment by sekineh** [comment]
@Stargateur 
1st line (cinst) is for winpcap (I guess it contains driver and dlls).
2nd line is for WpdPack.zip which is a sdk for winpcap (I guess it contains .h files).

**Comment by Stargateur** [comment]
See https://github.com/rust-pcap/pcap/pull/262, I found the problem (I think).
