### ISSUE TITLE
Setting direction to PCAP_D_OUT is not supported on BPF

### ISSUE THREAD

**Issue by gruberb** [rust-pcap/pcap#267]
I am trying to capture outbound traffic on my M1 Mac, and setting the direction to out:

```
cap.direction(Direction::Out).unwrap();
```

results in an error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PcapError("Setting direction to PCAP_D_OUT is not supported on BPF")'
```

**Comment by Wojtek242** [comment]
That's an error from the underlying libpcap library. [That's what `PcapError` is indicating](https://github.com/rust-pcap/pcap/blob/main/src/lib.rs#L108). 

To resolve the error, please consult the [libpcap documentation](https://www.tcpdump.org/manpages/pcap_setdirection.3pcap.html). However, a brief inspection of the underlying libpcap call reveals the following:
> pcap_setdirection() isn't necessarily fully supported on all platforms; some platforms might return an error for all values, and some other platforms might not support PCAP_D_OUT. 

It does not appear like we can help here.

**Comment by Wojtek242** [comment]
If you show you can achieve this with the tcpdump program though then this would be an issue in the pcap crate and I'll reopen it.
