### ISSUE TITLE
Scatter-gather lists for SendQueue

### ISSUE THREAD

**Issue by qrnch-jan** [rust-pcap/pcap#271]
When an application needs to send raw packets at a very high rate, where packets only change partially, they can use `sendmsg()` and scatter-gather lists on unixy platforms.

On Windows it's slightly more complicated.  There are no easy-to-use raw sockets, so we typically rely on winpcap/npcap for sending raw packets.  However, pcap does not support scatter-gather lists for packets.

Furthermore, sending packet-by-packet on Windows is _abysmally_ slow.  To facilitate high-speed transmissions winpcap/npcap uses  sendqueues which allow packets to be batched up in user land, requiring only one transition to kernel to send all queued packets in one go.

For portable applications that use scatter-gather lists, the Windows code needs to first merge the packets and then add them to the sendqueue, requiring an extra layer of copies.

It would be nice if it were possible to queue up packets using `&[IoSlice]`'s.  This would eliminate one extra layer of copies, and would enable some higher level of interface parity with code that uses `sendmsg()` from the `nix` crate.  (Though note that `IoSlice` is from std).

**Comment by Wojtek242** [comment]
Resolved by #272
