### ISSUE TITLE
Why deprecated pcap_loop method

### ISSUE THREAD

**Issue by guoxiangCN** [rust-pcap/pcap#293]

**Comment by Stargateur** [comment]
can you be more precise ? this method doesn't exist.

**Comment by guoxiangCN** [comment]
Thanks for you reply! 
It appears in the source code, but it is not released to users 
Perhaps it is an api introduced by a higher version?
https://github.com/rust-pcap/pcap/blob/main/src/raw.rs#L122

**Comment by Stargateur** [comment]
this method is not very useful, this pcap crate purpose is not to expose low level pcap call, you can find an exemple of how to loop over packets here https://github.com/rust-pcap/pcap/blob/main/examples/iterprint.rs

**Comment by Wojtek242** [comment]
@Stargateur is correct. So far, everybody's needs are satisfied with what's in this crate.

If you think there is a use for `pcap_loop` beyond what this crate already provides and that can be exposed through the crate's Rust API, please submit a PR.
