### ISSUE TITLE
GATs have been stable for a while now, better iterators when?

### ISSUE THREAD

**Issue by keogami** [rust-pcap/pcap#297]
https://github.com/rust-pcap/pcap/blob/ff3eb2369dd5d6a2ba20063409bf4829a94aeabf/src/codec.rs#L6-L7

It really is an extreme pain to iterate over packets right now. But with GATs it should be a lot more present now.

**Comment by Stargateur** [comment]
https://github.com/rust-pcap/pcap/pull/294

**Comment by stappersg** [comment]
On Wed, May 03, 2023 at 09:35:35AM -0700, Keogami wrote:
> Closed #297 as completed.
> 

Is that a "#294 works for me" ???

If so, update #294

**Comment by Stargateur** [comment]
@stappersg you are now blocked my patience have limit. you are a pain in this project.
