### ISSUE TITLE
Tcp Reassembly

### ISSUE THREAD

**Issue by evanzhang87** [rust-pcap/pcap#303]
Hello, previously I was using `google/gopacket` for TCP stream analysis, but as the traffic increased, the performance of Golang did not meet my expectations, especially in terms of memory usage. So I decided to try doing the same thing using Rust. There is a critical part in my project which involves TCP Reassembly, but it seems that I cannot directly implement it within this project because there is no TCP packet parsing. I'd like to know if there are plans to support this aspect in the future.

**Comment by Stargateur** [comment]
I speak in my name, no at all the purpose of this project. Unfortunately I do not know any crates that do tcp reassembly, maybe https://github.com/smoltcp-rs/smoltcp do it.

**Comment by Wojtek242** [comment]
As `pcap` is merely around `libpcap` it cannot do that. See [here](https://stackoverflow.com/a/12981818). @Stargateur has made a good suggestion on what you could use instead.
