### ISSUE TITLE
Reading PCAP files?

### ISSUE THREAD

**Issue by spirrello** [rust-pcap/pcap#342]
Hi there,

Is it possible to use this for viewing PCAP files and searching for protocol payloads such as HTTP or DNS?  Can you provide an example?

**Comment by Stargateur** [comment]
https://github.com/rust-pcap/pcap/blob/main/examples/stdin.rs#L39

**Comment by Wojtek242** [comment]
As pointed out above, it is possible. Please have a browse through the docs page: https://docs.rs/pcap/latest/pcap/?search=file.
