### ISSUE TITLE
Unrecoverable error when executing without driver installed

### ISSUE THREAD

**Issue by grantshandy** [rust-pcap/pcap#362]
Hello, thanks for maintaining this great library. For some context about my question, I'm trying to implement a feature in my application where it automatically disables features that require `pcap` when the drivers aren't installed, like wireshark does here on windows:

![image](https://github.com/user-attachments/assets/c3265825-86ca-4cd1-8758-ada001373b09)

However, after uninstalling the npcap driver on my machine and running my program, I find that it doesn't panic or print any errors, it just exits *before* `main` runs and I get `exit code: 0xc0000135, STATUS_DLL_NOT_FOUND`. I was expecting crate calls to methods like `Device::list` to just return an error variant like `pcap::Error::NoDriver` to indicate that it couldn't find the `.dll`, but I see now it's much more all-or-nothing.

I'm admittedly not very familiar with windows' linking or executables, so I know I'm not entitled to an entire explanation 😅, but is this inside the scope of this library or am I just using it incorrectly? Is there a way I could do this by emitting special flags in my build script and then load the library myself dynamically (which I honestly have no idea where to start with) - or is this type of usage impossible with the library as it stands? I haven't made any changes to link with `wpcap.lib` in my build script and my application compiles fine, but can't run.

If any changes need to be made to the library so users can do this sort of thing I'm willing to contribute the best I can if I knew where to look. Thanks!

**Comment by Stargateur** [comment]
it would need we do dynamic loading of the libpcap. For now we require OS to do it for us like 99.9% of library.

**Comment by grantshandy** [comment]
@Stargateur do you think the library would accept a PR for dynamic loading via a feature flag?

**Comment by Wojtek242** [comment]
I don't think it should be the responsibility of this library to do what you are describing. I would propose you go up one step and conditionally/dynamically load `pcap` based on the presence of `libpcap`. No idea how to do it, but @Stargateur is right that you'll have to figure out how to do it with the OS.
