### ISSUE TITLE
PcapError("send error: PacketSendPacket failed: A device attached to the system is not functioning.  (31)")

### ISSUE THREAD

**Issue by NextrixVFX** [rust-pcap/pcap#363]
So when i run my script that either can send a spoofed arp packet or a deauth packet i get the same issue this guy's having
https://stackoverflow.com/questions/76928614/i-get-error-31-when-using-pcap-sendpacket-with-real-wi-fi-device-but-it-works-f
my wlan adapter is the alfa awus036nha.
ethernet and loopback works fine.
however when im in monitor mode i get this error: PcapError("send error: PacketSendPacket failed: The I/O operation failed because network media is disconnected or wireless access point is out of range.  (2150891551)")

my trimmed-down capture code (im new to rust):

```
fn select_nic() -> Device {
    let device_list : Vec<Device> = pcap::Device::list().unwrap();

    for i in 0..device_list.len() { 
        println!("Device {}: {:?}\n", i, device_list[i].desc);
    }

    let input: usize = get_input("Select device:\t").trim().parse().unwrap();

    let network_interface: Device = device_list[input].clone();

    return network_interface;
}
let network_interface: Device = select_nic();
let cap: Capture<pcap::Active> = Capture::from_device(nic.clone()).unwrap().open().unwrap();
```
wireshark and any other programs that use npcap work fine with wlan and i get this same issue across devices

## EDIT: it works perfectly on kali linux this it just a windows issue. The error occurs when i send the packet, not select the device...

**Comment by Wojtek242** [comment]
Unfortunately that is not an error within this library, `pcap`, which are merely Rust bindings for `libpcap`. `PcapError` indicates that the error originates in `libpcap` so you will need to look there for a solution.

**Comment by NextrixVFX** [comment]
alr tysm
